version: '3.8'

services:
  mi-web:
    image: nginx:alpine
    container_name: Frencores_Web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./mi-web-react/dist:/usr/share/nginx/html
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

